name: Docker Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      env:
        DOCKER_BUILDKIT: '1'
      run: |
        DOCKER_REPO=`echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'`;
        DOCKER_TAG=`git rev-parse --short HEAD`;
        docker build . --file Dockerfile --build-arg VCS_REF="$DOCKER_TAG" --tag "docker.pkg.github.com/$DOCKER_REPO/tekkit-classic-server:$DOCKER_TAG"
    - name: Login to Docker Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username lolpants --password-stdin
    - name: Push to Docker Registry
      run: |
        DOCKER_REPO=`echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'`;
        docker push "docker.pkg.github.com/$DOCKER_REPO/tekkit-classic-server"
      if: github.ref == 'refs/heads/master'
